[workspace]
members = [
    "crates/quadbench-app",
    "crates/quadbench-betaflight",
    "crates/quadbench-core",
    "crates/quadbench-input",
    "crates/quadbench-physics",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
eframe = "0.36.1"
gilrs = "0.11.2"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tungstenite = "0.30.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
codegen-units = 1
