[package]
name = "quadbench-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "quadbench"
path = "src/main.rs"

[dependencies]
eframe.workspace = true
quadbench-betaflight = { path = "../quadbench-betaflight" }
quadbench-core = { path = "../quadbench-core" }
quadbench-input = { path = "../quadbench-input" }
quadbench-physics = { path = "../quadbench-physics" }
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
embed-manifest = "1.5.0"
